# Generated by Django 4.2.5 on 2024-02-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_course',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
