# Generated by Django 4.2.5 on 2024-03-02 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0001_initial'),
        ('students', '0003_my_enrolls_delete_my_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('my_course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='mycourse', to='admins.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='My_Enrolls',
        ),
    ]
