# Generated by Django 4.2.5 on 2023-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('time_added', models.DateTimeField()),
            ],
        ),
    ]
