# Generated by Django 4.2.5 on 2023-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisment',
            name='area',
        ),
        migrations.AddField(
            model_name='advertisment',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisment',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
