# Generated by Django 4.2.5 on 2023-12-25 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 16, 59, 29, 97099, tzinfo=datetime.timezone.utc)),
        ),
    ]
