# Generated by Django 4.2.5 on 2023-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0002_remove_advertisment_area_advertisment_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='area',
            field=models.CharField(choices=[('top', 'Top'), ('button', 'Button'), ('left', 'left'), ('right', 'Rignt')], default=1, max_length=255),
        ),
    ]
