# Generated by Django 4.2.5 on 2024-01-05 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srm', '0006_alter_advertisment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 14, 13, 29, 653825, tzinfo=datetime.timezone.utc)),
        ),
    ]
